version: '2'
services:
  # Front-end envoy proxy that handles all outward facing traffic.
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy.yaml
    networks:
      - mesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  # Internal service, provides some data.
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - ./service/envoy.yaml:/etc/envoy.yaml
    networks:
      mesh:
        aliases:
          - service
    expose:
      - "80"

  # Internal service, provides a back-end key/value store.
  grpc_service:
    build:
      context: ./grpc_service
      dockerfile: Dockerfile
    volumes:
      - ./gen/kv_pb2.py:/code/kv_pb2.py
      - ./gen/kv_pb2_grpc.py:/code/kv_pb2_grpc.py
      - ./grpc_service/envoy.yaml:/etc/envoy.yaml
    networks:
      mesh:
        aliases:
          - grpc_service
    expose:
      - "80"

networks:
  mesh: {}
